# Generated by Django 4.1.1 on 2023-04-02 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Medical', 'Medical'), ('Stationary', 'Stationary'), ('Print', 'Print'), ('General Store', 'General Store'), ('grocery', 'grocery'), ('books', 'books'), ('food', 'food'), ('Others', 'Others')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(default='media/images/default.jpg', upload_to='media/images')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Stores.store')),
            ],
        ),
    ]
