# Generated by Django 4.1.1 on 2023-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Medical', 'Medical'), ('Stationary', 'Stationary'), ('Print', 'Print'), ('General Store', 'General Store'), ('Grocery', 'Grocery'), ('Books', 'Books'), ('Food', 'Food'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
