# Generated by Django 4.1.1 on 2023-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_orderitem_remove_cartitem_cart_cartitem_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
