# Generated by Django 4.1.1 on 2023-04-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
        ('accounts', '0002_alter_buyer_user_alter_seller_user'),
        ('Orders', '0004_order_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('deliveryaddress', models.TextField()),
                ('status', models.CharField(choices=[('N', 'Not Delivered'), ('D', 'Delivered')], default='N', max_length=1)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerwise_orders', to='accounts.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Orders.sellerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.product')),
            ],
        ),
    ]
