# Generated by Django 4.1.1 on 2023-04-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_sellerorder_sellerorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sellerorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='SellerOrder',
        ),
        migrations.DeleteModel(
            name='SellerOrderItem',
        ),
    ]
