# Generated by Django 4.1.1 on 2023-04-14 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_alter_store_category'),
        ('accounts', '0002_alter_buyer_user_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='Stores.store'),
            preserve_default=False,
        ),
    ]
